### ISSUE TITLE
Instrument Apache CXF's JAX-RS implementation

### ISSUE THREAD

**Issue by punitsi** [micrometer-metrics/micrometer#1364]
Metrics http_server_requests_seconds_count in Spring Boot application with version 2.0.8.Release exposed using spring actuator contains uri as "UNKNOWN". Spring Boot application is using cxf-spring-boot-starter-jaxrs for exposing rest endpoints.
I have added micrometer-registry-prometheus dependency in my project.
```
http_server_requests_seconds_count{exception="None",method="POST",status="200",uri="UNKNOWN",} 2.0
```

Actual
```
http_server_requests_seconds_count{exception="None",method="POST",status="200",uri="UNKNOWN",} 2.0
```
Expected:
```
http_server_requests_seconds_count{exception="None",method="GET",status="200",uri="/sayHello",} 2.0
```

 micrometer-cxf implementation i believe similiar to micrometer-jersey2 should resolve the issue.

**Comment by shakuzen** [comment]
I don't have any CXF experience, but I would first advise trying with the latest versions, as something may have been fixed. If it is not fixed in the latest versions, please provide a sample application where we can reproduce the problem to better understand what is missing.

**Comment by mweirauch** [comment]
As already stated [here](https://stackoverflow.com/questions/55517471/metrics-http-server-requests-seconds-count-in-spring-boot-application-using-cxf#comment97771821_55517471), Apache CXF is an alternative JAX-RS implementation, which differs from the `micrometer-jersey2` one.

So I think one would need a Apache CXF specific implementation to produce HTTP request metrics like we do for Jersey2. (The implementation then should produce the same style of metrics like WebMVC, WebFlux and Jersey2 to keep these in line.)

**Comment by marcingrzejszczak** [comment]
Isn't this fixed via https://github.com/apache/cxf/pull/1346# ?

**Comment by catia-talend** [comment]
Hello @marcingrzejszczak .

This issue still occurs when using CXF 4.x (combined with Spring Boot 3.x). URI tag is always UNKNOWN for http_server_requests. cxf_server_requests are working fine, but not http_server_requests.

I have attached a [pet project](https://github.com/micrometer-metrics/micrometer/files/13829036/example.zip) to reproduce the issue. This example project is based on https://github.com/apache/cxf/tree/main/distribution/src/main/release/samples/jax_rs/spring_boot .
In this project, we're using CXF 4.0.3 and Spring Boot 3.1.1 .

Simply run:
```
curl -s http://127.0.0.1:8080/services/sayHello/world
Hello world, Welcome to CXF RS Spring Boot World!!!

curl -s http://127.0.0.1:8080/services/notFound


curl -s http://127.0.0.1:8080/actuator/prometheus | grep requests_seconds_count
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="CLIENT_ERROR",status="404",uri="NOT_FOUND",} 1.0
http_server_requests_seconds_count{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="UNKNOWN",} 1.0
cxf_server_requests_seconds_count{exception="None",method="GET",operation="sayHello",outcome="SUCCESS",status="200",uri="/services/sayHello/{a}",} 1.0
```
Thank you and kind regards.

**Comment by marcingrzejszczak** [comment]
Accidentally closed this issue

**Comment by marcingrzejszczak** [comment]
I looked into this and the problem is not in the CXF instrumentation as you stated that because it's working fine. There's a problem in the `DefaultServerRequestObservationConvention` in Spring MVC that does not have the `pathPattern` set and can't resolve the URL pattern.

```java
protected KeyValue uri(ServerRequestObservationContext context) {
		if (context.getCarrier() != null) {
			String pattern = context.getPathPattern();
```

**Comment by bclozel** [comment]
I'm confused. `cxf_server_requests` are working fine because the CXF instrumentation knows how to fetch the pattern information from the JAX-RS annotations. Spring's `http_server_requests` is about the instrumentation of Spring MVC and Spring WebFlux; this has no knowledge about CXF URI patterns. To me this is not a Spring bug, but rather a limitation in the sense that it won't get the pattern information for libraries that we don't know of.

**Comment by marcingrzejszczak** [comment]
So in fact that metric should be surpressed by the CXF one?

**Comment by bclozel** [comment]
My point is, if the Spring instrumentation cannot know about the URI pattern, it will use a default `UNKNOWN` tag for this. If the application is not using Spring MVC nor Spring WebFlux endpoints, I don't see the point in setting up the observation filter; the app should rely on the CXF instrumentation only.

**Comment by marcingrzejszczak** [comment]
OK, so to sum it up. I'm closing this issue because there's no bug neither in the CXF nor MVC instrumentation. It should be either this or that, meaning that if you're using the CXF instrumentation you should not be using the MVC one (through the observation filter).

Thanks @bclozel for your help!
