### ISSUE TITLE
Prometheus Push Gateway - error during metrics collection

### ISSUE THREAD

**Issue by lupo112** [micrometer-metrics/micrometer#243]
Hi

I am using prometheus gateway and I have a problem. Gateway reporting this error:

```
An error has occurred during metrics collection:

gathered metric family process_start_time_seconds has help "The start time of the Java virtual machine" but should have "Start time of the process since unix epoch in seconds."
```

So it cannot be scraped any data from push gateway into prometheus server.

Any idea how to solve this?

Used versions (all latest):
```
Micrometer (core, spring-legacy, registry-prometheus) 1.0.0-rc.4
Prometheus Java client (simpleclient, pushgateway) 0.1.0
Prometheus Push Gateway 0.4.0
```

**Comment by mweirauch** [comment]
Ugh... So the Pushgateway is spitting that out you say? Or is it Prometheus actually when it is scraping the Pushgateway?
* Please provide the output from the prometheus endpoint of your app (`/prometheus` by default) including the `TYPE` and `HELP` comments for `process_start_time_seconds`.
* Also the scrape config for the Pushgateway within Prometheus would be interessing. (topic `honor_labels` ...).
* And if available any Pushgateway configuration.
* If possible the output of the `/metrics` endpoint of the Pushgateway itself.

Would like to reproduce what is happening. Perhaps there's a mismatch between the `process_start_time_seconds` and it's help of the Pushgateway itself and that of the pushed metrics to it which are all exposed under the same `/metrics` endpoint. (Sounds likely)

**Comment by lupo112** [comment]
Problem is on the `/metrics` endpoint of the Pushgateway which returns:

```
An error has occurred during metrics collection:

gathered metric family process_start_time_seconds has help "The start time of the Java virtual machine" but should have "Start time of the process since unix epoch in seconds."
```
App produces metrics correctly:
```
# HELP jvm_buffer_total_capacity_bytes An estimate of the total capacity of the buffers in this pool
# TYPE jvm_buffer_total_capacity_bytes gauge
jvm_buffer_total_capacity_bytes{id="direct",} 1.34808549E8
jvm_buffer_total_capacity_bytes{id="mapped",} 0.0
# HELP jvm_memory_used_bytes The amount of used memory
# TYPE jvm_memory_used_bytes gauge
jvm_memory_used_bytes{area="nonheap",id="Code Cache",} 2.6257728E7
jvm_memory_used_bytes{area="nonheap",id="Metaspace",} 8.7563768E7
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",} 1.142756E7
jvm_memory_used_bytes{area="heap",id="PS Eden Space",} 3.41259704E8
jvm_memory_used_bytes{area="heap",id="PS Survivor Space",} 2.75838E7
jvm_memory_used_bytes{area="heap",id="PS Old Gen",} 1.38414976E8
# HELP process_uptime_seconds The uptime of the Java virtual machine
# TYPE process_uptime_seconds gauge
process_uptime_seconds 1443.387
# HELP logback_events_total Number of error level events that made it to the logs
# TYPE logback_events_total counter
logback_events_total{level="error",} 0.0
logback_events_total{level="warn",} 0.0
logback_events_total{level="info",} 43.0
logback_events_total{level="debug",} 0.0
logback_events_total{level="trace",} 0.0
# HELP process_start_time_seconds The start time of the Java virtual machine
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.511348010888E9
# HELP system_cpu_count The number of processors available to the Java virtual machine
# TYPE system_cpu_count gauge
system_cpu_count 4.0
# HELP jvm_memory_committed_bytes The amount of memory in bytes that is committed for  the Java virtual machine to use
# TYPE jvm_memory_committed_bytes gauge
jvm_memory_committed_bytes{area="nonheap",id="Code Cache",} 2.6476544E7
jvm_memory_committed_bytes{area="nonheap",id="Metaspace",} 8.9956352E7
jvm_memory_committed_bytes{area="nonheap",id="Compressed Class Space",} 1.2099584E7
jvm_memory_committed_bytes{area="heap",id="PS Eden Space",} 7.4973184E8
jvm_memory_committed_bytes{area="heap",id="PS Survivor Space",} 4.8234496E7
jvm_memory_committed_bytes{area="heap",id="PS Old Gen",} 2.61095424E8
# HELP jvm_memory_max_bytes The maximum amount of memory in bytes that can be used for memory management
# TYPE jvm_memory_max_bytes gauge
jvm_memory_max_bytes{area="nonheap",id="Code Cache",} 2.5165824E8
jvm_memory_max_bytes{area="nonheap",id="Metaspace",} -1.0
jvm_memory_max_bytes{area="nonheap",id="Compressed Class Space",} 1.073741824E9
jvm_memory_max_bytes{area="heap",id="PS Eden Space",} 1.322254336E9
jvm_memory_max_bytes{area="heap",id="PS Survivor Space",} 4.8234496E7
jvm_memory_max_bytes{area="heap",id="PS Old Gen",} 2.838495232E9
# HELP http_server_requests_duration_seconds Timer of servlet request
# TYPE http_server_requests_duration_seconds summary
http_server_requests_duration_seconds_count{exception="None",method="GET",status="200",uri="/prometheus",} 6.0
http_server_requests_duration_seconds_sum{exception="None",method="GET",status="200",uri="/prometheus",} 0.162618748
http_server_requests_duration_seconds_max{exception="None",method="GET",status="200",uri="/prometheus",} 0.0
# HELP jvm_buffer_count An estimate of the number of buffers in the pool
# TYPE jvm_buffer_count gauge
jvm_buffer_count{id="direct",} 29.0
jvm_buffer_count{id="mapped",} 0.0
# HELP jvm_buffer_memory_used_bytes An estimate of the memory that the Java virtual machine is using for this buffer pool
# TYPE jvm_buffer_memory_used_bytes gauge
jvm_buffer_memory_used_bytes{id="direct",} 1.3480855E8
jvm_buffer_memory_used_bytes{id="mapped",} 0.0
```

Pushgateway configuration is not present, running only with parameters for persistence file and listen address.

**Comment by mweirauch** [comment]
Ok, I assume it's mixing up the Pushgateway metrics and the pushed metrics and the HELP text associated with the metric. I can try reproducing when I find the time. Worth a read: https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels
Perhaps you can try adding an instance label or some other differentiator tag so that the pushed process metric is different from the pushgateway metric.

If you are in Spring:
```
    @Bean
    MeterRegistryConfigurer configurer(
            @Value("${spring.application.name}") String applicationName) {
        return (registry) -> registry.config().commonTags("application", applicationName);
    }
```
This just serves as an example. Ideally it should be an "instance" tag. Perhaps this solves it. If not, I see trouble ahead when we need to rename the description. (Other more intrusive option, disable writing descriptions: `spring.metrics.prometheus.descriptions=false` if that helps. Untested.)

**Comment by jkschneider** [comment]
@mweirauch I think an additional tag would blow it up too (but not sure), since you'd have one metric without the tag and one with. That violates another tenant of Prometheus ids -- that tags can't "appear and disappear".

**Comment by jkschneider** [comment]
Prometheus has a hard requirement for description text. Turning off `spring.metrics.prometheus.descriptions` just results in us sending a single blank (since an empty string is also evidently unacceptable).

**Comment by lupo112** [comment]
Thanks for the suggestions. However, it does not help. I already had defined tags `application` and `instance`. See the image:

![pushgateway](https://user-images.githubusercontent.com/1206903/33373413-1b2d3562-d502-11e7-94ec-19643a24bd1c.PNG)

After setting of `spring.metrics.prometheus.descriptions` to `false`, it does not help either. The output of the gateway (`/metrics`) is:

```
An error has occurred during metrics collection:

gathered metric family process_start_time_seconds has help "" but should have "Start time of the process since unix epoch in seconds."
```

Any other ideas to solve this problem?

**Comment by jkschneider** [comment]
It's insane to me that description text is validated in a way that causes hard failure, but I suppose we can just change the description text to match.

**Comment by jkschneider** [comment]
@lupo112 I cannot reproduce this here. Steps I took:

```
docker pull prom/pushgateway
docker run -p 9091:9091 prom/pushgateway
```

Sample code:

```java
public class UptimeMetricsSample {
    public static void main(String[] args) throws IOException {
        PrometheusMeterRegistry registry = SampleRegistries.prometheusPushgateway();
        registry.config().commonTags("instance", "sample-host");
        new UptimeMetrics().bindTo(registry);
        new PushGateway("localhost:9091").pushAdd(registry.getPrometheusRegistry(), "samples");
    }
}
```

The output of `localhost:9091/metrics` is:

![image](https://user-images.githubusercontent.com/1697736/33387564-3c73ed4c-d4f3-11e7-8009-59b0b1cb0a73.png)

Looks like the pushgateway _overrode_ the description text Micrometer provided, but it doesn't throw an error?

**Comment by mweirauch** [comment]
Also can't reproduce. Tried pushgateway from `0.3.0` to `v0.4.0`.

**Comment by jkschneider** [comment]
I'll close this for now, but am willing to look at it again @lupo112 if you can provide further detail allowing us to reproduce.

**Comment by lupo112** [comment]
Sorry for late response...

After I use your code, pushgateway still returns:
```
An error has occurred during metrics collection:

gathered metric family process_start_time_seconds has help "The start time of the Java virtual machine" but should have "Start time of the process since unix epoch in seconds."
```
Pushgateway was clean (manually cleared in UI), restarted, no other instances has any access to this gateway, only the sample code. Before running the code, all pushgateway metrics was visible in the `/metrics` endpoint. After running the sample code, it ends with the error above.

However, I was trying to check it also on localhost. I was not able to reproduce this problem on local instances (win). However, on server I am using binaries for linux (I think installed through apt), see screen:

![image](https://user-images.githubusercontent.com/1206903/33545351-2fe4e664-d8de-11e7-8de0-911e95771403.png)

**Comment by lupo112** [comment]
I also found these errors:

```
An error has occurred during metrics collection:

3 error(s) occurred:
* collected metric push_time_seconds label:<name:"application" value:"iconnect-test-***" > label:<name:"instance" value:"***" > label:<name:"job" value:"publish" > gauge:<value:1.51238024851149e+09 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric process_uptime_seconds label:<name:"application" value:"iconnect-test-***" > label:<name:"instance" value:"***" > label:<name:"job" value:"publish" > gauge:<value:417589.748 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* gathered metric family process_start_time_seconds has help "The start time of the Java virtual machine" but should have "Start time of the process since unix epoch in seconds."
```

`***` = IP address

**Comment by BogdanCeausu** [comment]
I have the same problem, tried using a MeterFilter to deny the respective metric, but with no success.

**Comment by jkschneider** [comment]
Fixed with 799961dc

**Comment by kjan** [comment]
Hello,

Is this issue really solved  ?
Because I still see the same error message  when pushing the metrics with **Micrometer 0.5.6/Spring Boot 2.0.4** to the Prometheus Pushgateway.


```

Pushgateway

branch               HEAD
buildDate            20180615-16:11:56
buildUser            root@c95e387ff56a
goVersion            go1.10.3
revision             231071b3e0a57b58df717bba5f4e5d88cac95389
version              0.5.2
```



Log of Prometheus Pushgateway : 

```
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 22 Aug 2018 09:07:03 GMT
< Content-Length: 228
<
An error has occurred during metrics collection:

gathered metric family process_start_time_seconds has help "Start time of the process since unix epoch." but should have "Start time of the process since unix epoch in seconds."
```

**Comment by mweirauch** [comment]
Please see #758 for further details. The PR might fix it by adjusting the metric name we expose. But in the end it's a regression in pushgateway:0.5.0+ which is being worked on. In the meantime, you can downgrade to pushgateway:0.4.0 in case you are not requiring any features/fixes from the 0.5.x line.
