### ISSUE TITLE
Log warning when a registry is added to composite after meter registration

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#6908]
I also think we should pursue adding a warning log so that users who can do all setup before registering metrics can avoid surprises like this and others (such as the values being recorded before a non-composite registry is added being dropped).

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/pull/6846#pullrequestreview-3480848960_

See also https://github.com/micrometer-metrics/micrometer/issues/6811#issuecomment-3451518473

**Comment by shakuzen** [comment]
It could be done in a separate issue, but probably there is some documentation update that should accompany this. Perhaps the warning logged could link to the documentation (although that's potentially fragile as the link needs to always work going forward).

**Comment by jonatan-ivanov** [comment]
Fixed by #7322

**Comment by shakuzen** [comment]
We're still missing the documentation part of this issue. I'll open a new issue for that.
